apiVersion: batch/v1
kind: Job
metadata:
  name: load-test
spec:
  template:
    spec:
      containers:
      - name: load-tester
        image: argoproj/load-tester:latest
        command: [sh, -c, -x, -e]
        args:
        - |
          wrk -t10 -c40 -d45s -s report.lua http://canary-demo-preview/color
          jq -e '.errors_ratio <= 0.05 and .latency_avg_ms < 100' report.json
