apiVersion: v1
kind: Service
metadata:
  name: istio-rollout
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 30547
  selector:
    app: istio-rollout
  type: NodePort
