apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollout-vsvc
spec:
  #gateways:
  #- istio-rollout-gateway
  hosts:
  #- istio-rollout.dev.argoproj.io
  - frontend
  - canary-frontend
  http:
  - fault:
      abort:
        percentage:
          value: 0.0
        httpStatus: 500
    route:
    - destination:
        host: canary-frontend #.default.svc.cluster.local
        subset: frontend
  - name: primary
    route:
    - destination:
        host: frontend 
        #subset: stable # referenced in canary.stableService
      weight: 100 
    - destination:
        host: canary-frontend
        #subset: canary # referenced in canary.canaryService
      weight: 0 
---
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata: 
  name: canary-frontend-dr
spec:
  host: canary-frontend #.default.svc.cluster.local
  subsets:
  - name: frontend
    labels:
      app: frontend
