apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollout-vsvc
spec:
  gateways:
  - istio-rollout-gateway
  hosts:
  - frontend.local
  http:
  - name: primary
    route:
    - destination:
        host: frontend
        subset: stable
      weight: 100
    - destination:
        host: frontend
        subset: canary
      weight: 0
