apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollout-vsvc
spec:
  gateways:
  - istio-rollout-gateway
  hosts:
  - istio-rollout.dev.argoproj.io
  http:
  - fault:
      abort:
        percentage:
          value: 100.0
        httpStatus: 500
  - name: primary
    route:
    - destination:
        host: emailservice 
        subset: stable # referenced in canary.stableService
      weight: 100 
    - destination:
        host: emailservice
        subset: canary # referenced in canary.canaryService
      weight: 0 
