apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: rollout-vsvc
spec:
  hosts:
    - frontend
    - canary-frontend
  http:
    - route:
        - destination:
            host: frontend
          weight: 100
        - destination:
            host: canary-frontend
          weight: 0
