apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollout-vsvc
spec:
  gateways:
  - istio-rollout-gateway
  hosts:
  - frontend.local
  http:
  - name: primary
    route:
    - destination:
        host: frontend
        subset: stable
      weight: 100
    - destination:
        host: canary-frontend
        subset: canary
      weight: 0
  - fault:
      abort:
        httpStatus: 500
        percentage:
          value: 10 # 10% of requests will be aborted with a 500 error
    route:
    - destination:
        host: frontend
        subset: canary
