apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fault-vsvc
spec:
  hosts:
  - emailservice
  http:  
  - fault:
      abort:
        percent: 100
        httpStatus: 500
  - route:
    - destination:
        host: emailservice 

