apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata: 
  name: emailservice-vs
spec:
  hosts:
  - emailservice.default.svc.cluster.local
  http:
  - fault:
      abort:
        percentage:
          value: 100.0
        httpStatus: 500
    route:
    - destination:
        host: emailservice.default.svc.cluster.local
        subset: email
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata: 
  name: emailservice-dr
spec:
  host: emailservice.default.svc.cluster.local
  subsets:
  - name: email
    labels:
      app: emailservice
