apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata: 
  name: checkoutservice-vs
spec:
  hosts:
  - checkoutservice.default.svc.cluster.local
  http:
  - fault:
      abort:
        percentage:
          value: 20.0
        httpStatus: 500
    route:
    - destination:
        host: checkoutservice.default.svc.cluster.local
        subset: checkout
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata: 
  name: checkoutservice-dr
spec:
  host: checkoutservice.default.svc.cluster.local
  subsets:
  - name: checkout
    labels:
      app: checkoutservice
