apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata: 
  name: frontend-vs
spec:
  hosts:
  - frontend.default.svc.cluster.local
  http:
  - fault:
      abort:
        percentage:
          value: 0.0
        httpStatus: 500
    route:
    - destination:
        host: frontend.default.svc.cluster.local
        subset: frontend
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata: 
  name: frontend-dr
spec:
  host: frontend.default.svc.cluster.local
  subsets:
  - name: canary
    labels:
      app: frontend
