apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: emailservice-fault-injection
spec:
  hosts:
  - emailservice.default.svc.cluster.local
  http:
  - fault:
      abort:
        httpStatus: 500
        percentage:
          value: 100
    route:
    - destination:
        host: emailservice.default.svc.cluster.local
        port:
          number: 8080
