apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-ingress
 # Namespace, if using examples would be just application
spec:
  hosts:
  - frontend
  http:
  - route:
    - destination:
        host: emailservice
        port:
          number: 80
    # Inject faults, see https://istio.io/latest/docs/tasks/traffic-management/fault-injection/
    fault:  
      abort:
        httpStatus: 500
        percentage:
          value: 50
        
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend-destrule
spec:
  host: emailservice
  subsets:
  - name: frontend
