apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata: 
  name: productcatalogservice-vs
spec:
  hosts:
  - productcatalogservice.default.svc.cluster.local
  http:
  - fault:
      abort:
        percentage:
          value: 0.0
        httpStatus: 500
    route:
    - destination:
        host: productcatalogservice.default.svc.cluster.local
        subset: catalog
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata: 
  name: productcatalogservice-dr
spec:
  host: productcatalogservice.default.svc.cluster.local
  subsets:
  - name: catalog
    labels:
      app: productcatalogservice
