apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fault-vsvc
spec:
  hosts:
  - emailservice
  http:  
  - fault:
      abort:
        httpStatus: 500
        percent: 
          value: 100
    route:
    - destination:
        host: emailservice 

