apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: fault-injection-vsvc
spec:
  hosts:
    - canary-frontend
  http:
    - fault:
        abort:
          httpStatus: 500
          percentage:
            value: 10 # 10% of requests will be aborted with a 500 error
      route:
        - destination:
            host: canary-frontend
          weight: 100



#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata: 
#  name: canary-frontend-vs
#spec:
#  hosts:
#  - canary-frontend
#  http:
#  - name: faultPrimary 
#      fault:
#        abort:
#          percentage:
#            value: 0.0
#          httpStatus: 500
#      route:
#      - destination:
#          host: canary-frontend
        #subset: frontend
#---
#apiVersion: networking.istio.io/v1alpha3
#kind: DestinationRule
#metadata: 
#  name: canary-frontend-dr
#spec:
#  host: canary-frontend #.default.svc.cluster.local
#  subsets:
#  - name: frontend
#    labels:
#      app: frontend
